spring:
  datasource:
    url: jdbc:mysql://localhost:3306/toolbox?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: comet1
    hikari:
      minimum-idle: 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jwt:
    secret: 'comet2059!'
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
server:
  port: 8080
logging:
  file:
    name: log/toolbox.log
    max-size: 10MB
    max-history: 1000